git:
  depth: 5
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: pXRcZJtbeNHVxZLV954LMmluxP83mydKx9QLRpAoFVrCAOhVHt4VRFyT/gjBw3xFE/ZCvdAKBzJ5q2CLEID4cTgA2/KxMXgsxsSsD14As5zsYqxXEu8uel3rrXvPcKfXN+diV2ggCDCp4m3/mwbT3X3SYU0XSxpyRzcOWrlIkC4q7tDY6DJtQs3cVM6F9It2zzBUyJhXmZs1ceGG8sHg9ouoDhqLIFV89TLTbmk/Zerrju8zl1Bn1AXsRJp+7SYBA0HxNuxlKbXimQgwYDGgDHHRDAsTufQ2hpPRbfnPkuWT1y4t94SJmZgi+JZUo+sKVN13f3i6HDVvXbKhtHDQGHUKfnUF6cAuFX0ao+SQPpZ/jBR0b3VaJqiwrzogitzzWL8826CdED2xn9pu1rJr8BG/XCFZ6oWOQtTPhqJAmojnNqljSgR8KrqoS5YcGdKwNAuCb6tlUbpVMjrsQG3AE/TQlhcBiSO6GmG1IMdUuIO4qaR4h0DAfJrQjNdOuBb8Qz0vGm+x5Vf65J4/JgJybQRInt8ilTo2svLuj8MMN0GXsCWcgWfTxEkW/Fx+jnyjVdNE71dXXCb0a5GiHVEZRkBxr+kXUjWYz65CETctXL8Wybeyv3iIAN2DluSoz8Rs2lgKAZacWh3cGoi3pEURmd9LGHiAH6kx89vdqRHQ7UY=
script:
- nohup yarn test
