git:
  depth: 5
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: pedre87@gmail.com
  on:
    branch: master
  api_key:
    secure: jk836g+b4k/mpmZKA2EJrrox9gnEwgpyI4rZdMmrmNCrt2S07gjlvNTf3/ZxnL+QCaAIB5aYnw6BKtJEqWAlvhSc57dE83qMDUolGlNG/RijR6uLC8Ylu1tzrZnYPUgFq3/EZZCHSRPoso/sXyy9SSu996qVI2Us9CTRXLS/djtoe4TAFwC8simeF7dDCKrhR/45yutz1KYGtTa2s4ii1hRUZPIm4WrMEkOQMwQGioo4Q0gvxncLnJr5ZSl9y9obkYb2ib7XFhhYZB+tSicYUKProb9dVn/BVDZ8lKVJd+gOesLhLTWnKK0KeiDm8gGf9/qLoiB1n2EyGeZeyVl0w3FunczYAvT0on1fY3qid9aL7OVKhs7qvyvFojFLtVHFEyo8xpsuAanOKxkvXMX4RFR2eut0n/A+qx++9TvQkngQGnXiVAOObInXzm968Cukvq66dYSMarlQtl0XjSZ4Z2A3p5NkBbzG4MJrt4E8sKurQe0bguKIG3FJPN+nll/5JsB/a7/k82jlbftbE0IWJffgrfpTaQTNz/0v2GNh3bLY1Zs/lWcjFWvlarXTG9B6vao81ze4V5i9HNkbGtfye+tQ5N9D7OUKB1Fe+9URGZtqI5PILZsrlR81jNjLwOinBKpQ48yNdnteP8y8BrriNueZCBM497WgxW6SvE1Ro6c=
script:
- nohup yarn test
